export const products = [
  {
    id: 1,
    title: "Crash Twinsanity American",
    price: 179.99,
    rating: 5,
    tag: "Remaster",
    image: "/assets/CrashTwinsanityAmerican.webp",
  },
  {
    id: 2,
    title: "Crash Bandicoot 4: It's About Time",
    price: 249.99,
    rating: 5,
    tag: "Novo",
    image: "/assets/Crash-Bandicoot-4-capa.webp",
  },
  {
    id: 3,
    title: "Crash Team Racing Nitro-Fueled",
    price: 199.99,
    rating: 4,
    tag: "Promo",
    image: "/assets/Crash_Team_Racing_Nitro-Fueled_cover_art.webp",
  },
  {
    id: 4,
    title: "Crash Team Rumble",
    price: 149.99,
    rating: 3,
    tag: "Clássico",
    image: "/assets/Crash_Team_Rumble_cover_art.webp",
  },
  {
    id: 5,
    title: "Crash Bash",
    price: 129.99,
    rating: 4,
    tag: "Party",
    image: "/assets/Crash_of_the_Titans.webp",
  },
  {
    id: 6,
    title: "Crash Mind over Mutant",
    price: 99.99,
    rating: 5,
    tag: "Coleção",
    image: "/assets/Crash_Mind_over_Mutant_capa.webp",
  },
];
