export const products = [
  {
    id: 1,
    title: "Spyro 3 year of the dragon",
    price: 229.99,
    rating: 5,
    tag: "Remaster",
    image: "/assets/spyro-3-year-of-the-dragon-button.webp",
  },
  {
    id: 2,
    title: "Spyro: Season of Ice",
    price: 179.99,
    rating: 5,
    tag: "Clássico",
    image: "/assets/Spyro_Season_of_Ice.webp",
  },
  {
    id: 3,
    title: "Spyro: Reignited Trilogy",
    price: 169.99,
    rating: 4,
    tag: "Promo",
    image: "/assets/Spyro_Reignited_Trilogy.webp",
  },
  {
    id: 4,
    title: "Spyro: Dawn of the Dragon",
    price: 159.99,
    rating: 4,
    tag: "Aventura",
    image: "/assets/Spyro_dawn_of_the_dragon.webp",
  },
  {
    id: 5,
    title: "Spyro: 2",
    price: 149.99,
    rating: 3,
    tag: "",
    image: "/assets/Spyro_2_capa.webp",
  },
  {
    id: 6,
    title: "Spyro Eternal Night",
    price: 399.99,
    rating: 5,
    tag: "Coleção",
    image: "/assets/Eternal_Night.webp",
  },
];
